// SkyCall - single-file Node.js app (server + client) in one file.
// Save as server.js, run: npm init -y && npm install express ws cookie-parser
// Then: node server.js
//
// Notes:
// - Demo / proof-of-concept. In-memory users (not persistent).
// - Uses WebSocket for signaling and WebRTC for media.
// - Uses public STUN servers; for production add TURN and HTTPS.
// - For Render: set start command to `node server.js` and enable Web Service (PORT env used).
//
// Author: Generated by ChatGPT (GPT-5 Thinking mini)

const express = require('express');
const http = require('http');
const WebSocket = require('ws');
const cookieParser = require('cookie-parser');
const crypto = require('crypto');
const path = require('path');

const app = express();
app.use(express.urlencoded({ extended: false }));
app.use(express.json());
app.use(cookieParser());

const PORT = process.env.PORT || 3000;

// Simple in-memory user store: username -> { password, displayName, ws }
const users = {}; // For demo only

// Serve main page
app.get('/', (req, res) => {
  const username = req.cookies.username || '';
  res.setHeader('Content-Type', 'text/html; charset=utf-8');
  res.send(renderHTML(username));
});

// Registration endpoint
app.post('/api/register', (req, res) => {
  const { username, password, displayName } = req.body;
  if(!username || !password) return res.status(400).json({ error: 'username and password required' });
  if(users[username]) return res.status(409).json({ error: 'username taken' });
  users[username] = { password, displayName: displayName || username, ws: null };
  res.json({ ok: true });
});

// Login endpoint
app.post('/api/login', (req, res) => {
  const { username, password } = req.body;
  if(!username || !password) return res.status(400).json({ error: 'username and password required' });
  const user = users[username];
  if(!user || user.password !== password) return res.status(401).json({ error: 'invalid credentials' });
  // set cookie (not secure for production)
  res.cookie('username', username, { httpOnly: false });
  res.json({ ok: true, username, displayName: user.displayName });
});

// Logout
app.post('/api/logout', (req, res) => {
  res.clearCookie('username');
  res.json({ ok: true });
});

// Simple listing for search
app.get('/api/users', (req, res) => {
  const q = (req.query.q || '').toLowerCase();
  const list = Object.keys(users)
    .filter(u => u.toLowerCase().includes(q))
    .map(u => ({ username: u, displayName: users[u].displayName, online: !!users[u].ws }));
  res.json(list);
});

// HTTP server + WS for signaling
const server = http.createServer(app);
const wss = new WebSocket.Server({ server });

wss.on('connection', (ws, req) => {
  // Expect the client to send a "hello" message with username to register
  let user = null;

  ws.on('message', (data) => {
    try {
      const msg = JSON.parse(data.toString());
      handleMessage(ws, msg);
    } catch(e) {
      console.error('Invalid message', e);
    }
  });

  ws.on('close', () => {
    if(user && users[user]) {
      users[user].ws = null;
      broadcastUserStatus(user, false);
    }
  });

  function handleMessage(ws, msg) {
    const { type, from, to, payload } = msg;
    if(type === 'hello') {
      user = from;
      if(users[user]) {
        users[user].ws = ws;
      } else {
        // auto-register for convenience (demo)
        users[user] = { password: '', displayName: user, ws };
      }
      send(ws, { type: 'hello', ok: true, username: user });
      broadcastUserStatus(user, true);
      return;
    }

    // Relay messages to 'to' user if connected
    if(to && users[to] && users[to].ws) {
      const target = users[to].ws;
      send(target, msg);
    } else {
      // If target offline and it's an offer, respond with busy/offline
      if(type === 'call-offer' && (!to || !users[to] || !users[to].ws)) {
        send(ws, { type: 'call-failed', reason: 'user-offline', to });
      }
    }
  }
});

function send(ws, obj) {
  try { ws.send(JSON.stringify(obj)); } catch(e) {}
}

function broadcastUserStatus(username, online) {
  const msg = { type: 'user-status', username, online };
  wss.clients.forEach(c => {
    try { c.send(JSON.stringify(msg)); } catch(e) {}
  });
}

server.listen(PORT, () => {
  console.log(`SkyCall running on http://localhost:${PORT} (port ${PORT})`);
});

// HTML client (single-file)
function renderHTML(loggedUsername) {
  const html = `<!doctype html>
<html lang="ru">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<title>SkyCall — demo</title>
<style>
  :root{
    --bg:#0f1724; --card:#0b1220; --muted:#9aa9c3; --accent:#7c5cff; --danger:#ff6b6b;
    --glass: rgba(255,255,255,0.04);
  }
  *{box-sizing:border-box;font-family:Inter,ui-sans-serif,system-ui,-apple-system,"Segoe UI",Roboto,"Helvetica Neue","Noto Sans",Arial;}
  body{margin:0;background:linear-gradient(180deg,#071024 0%,#081426 60%);color:#e6eef8;min-height:100vh;display:flex;align-items:center;justify-content:center;padding:24px;}
  .app{width:100%;max-width:1100px;background:linear-gradient(180deg, rgba(255,255,255,0.02), rgba(0,0,0,0.06));border-radius:16px;box-shadow:0 10px 30px rgba(2,6,23,0.6);overflow:hidden;display:grid;grid-template-columns:360px 1fr;}
  .sidebar{padding:20px;background:var(--card);display:flex;flex-direction:column;gap:12px;}
  .brand{display:flex;gap:12px;align-items:center}
  .logo{width:44px;height:44px;border-radius:10px;background:linear-gradient(135deg,var(--accent),#4ce1b6);display:flex;align-items:center;justify-content:center;font-weight:700;color:#041025;font-size:18px}
  h1{font-size:18px;margin:0}
  .muted{color:var(--muted);font-size:13px}
  .card{background:var(--glass);padding:12px;border-radius:10px}
  .form-row{display:flex;flex-direction:column;gap:6px;margin-bottom:8px}
  input[type=text], input[type=password]{padding:10px;border-radius:8px;border:1px solid rgba(255,255,255,0.04);background:transparent;color:inherit}
  button{padding:10px 12px;border-radius:10px;border:0;background:var(--accent);color:#041025;font-weight:600;cursor:pointer}
  button.ghost{background:transparent;border:1px solid rgba(255,255,255,0.04);color:var(--muted)}
  .user-list{display:flex;flex-direction:column;gap:8px;margin-top:6px;overflow:auto}
  .user-item{display:flex;align-items:center;gap:10px;padding:8px;border-radius:10px;cursor:pointer}
  .user-item:hover{background:rgba(255,255,255,0.02)}
  .status-dot{width:10px;height:10px;border-radius:50%}
  .status-online{background:#2ee6a8}
  .status-off{background:#374258}
  .main{padding:28px;position:relative}
  .grid{display:grid;grid-template-columns:1fr 360px;gap:20px;height:calc(100vh - 120px)}
  .panel{background:linear-gradient(180deg, rgba(255,255,255,0.02), transparent);border-radius:12px;padding:14px;height:100%;display:flex;flex-direction:column}
  .video-wrap{background:#061026;border-radius:10px;flex:1;display:flex;align-items:center;justify-content:center;position:relative;overflow:hidden}
  video{width:100%;height:100%;object-fit:cover}
  .controls{display:flex;gap:10px;padding-top:10px;align-items:center}
  .btn-toggle{padding:10px 12px;border-radius:999px;border:0;background:rgba(255,255,255,0.04);cursor:pointer}
  .incoming{position:absolute;top:20px;left:50%;transform:translateX(-50%);background:linear-gradient(90deg,#3a2bff,#00e6b8);padding:16px 20px;border-radius:12px;z-index:20;display:flex;gap:12px;align-items:center;box-shadow:0 10px 30px rgba(0,0,0,0.4)}
  .small{font-size:13px}
  .footer{margin-top:auto;font-size:12px;color:var(--muted)}
  .search{display:flex;gap:8px}
  .search input{flex:1}
  .pill{background:rgba(255,255,255,0.03);padding:6px 8px;border-radius:999px;font-size:13px}
  .topbar{display:flex;justify-content:space-between;align-items:center;padding-bottom:10px}
  .note{font-size:13px;color:var(--muted)}
  .call-controls{display:flex;gap:8px;align-items:center}
  .danger{background:var(--danger);color:#fff}
  .hide{display:none}
  @media(max-width:900px){ .app{grid-template-columns:1fr} .grid{grid-template-columns:1fr} .sidebar{display:none} }
</style>
</head>
<body>
<div class="app" role="application" aria-label="SkyCall app">
  <div class="sidebar" id="sidebar">
    <div class="brand">
      <div class="logo">SC</div>
      <div>
        <h1>SkyCall</h1>
        <div class="muted">Простой demo звонков</div>
      </div>
    </div>

    <div class="card">
      <div id="auth-area">
        <div id="logged" class="hide">
          <div class="muted">Вы вошли как <strong id="me-name"></strong></div>
          <div style="margin-top:8px;display:flex;gap:8px">
            <button id="btn-logout" class="ghost">Выйти</button>
            <button id="btn-copy" class="ghost">Копировать логин</button>
          </div>
        </div>

        <div id="login-form">
          <div class="form-row">
            <label>Логин</label>
            <input id="login-username" type="text" placeholder="yourname" />
          </div>
          <div class="form-row">
            <label>Пароль</label>
            <input id="login-password" type="password" placeholder="password" />
          </div>
          <div style="display:flex;gap:8px">
            <button id="btn-login">Войти</button>
            <button id="btn-show-register" class="ghost">Регистрация</button>
          </div>
        </div>

        <div id="register-form" class="hide">
          <div class="form-row"><label>Логин</label><input id="reg-username" type="text" /></div>
          <div class="form-row"><label>Имя</label><input id="reg-display" type="text" /></div>
          <div class="form-row"><label>Пароль</label><input id="reg-password" type="password" /></div>
          <div style="display:flex;gap:8px">
            <button id="btn-register">Зарегистрироваться</button>
            <button id="btn-cancel-register" class="ghost">Отмена</button>
          </div>
        </div>
      </div>
    </div>

    <div class="card">
      <div class="search">
        <input id="search-q" placeholder="Поиск по логину..." />
        <button id="btn-search" class="ghost">Поиск</button>
      </div>
      <div class="user-list" id="user-list" style="margin-top:10px;max-height:320px"></div>
    </div>

    <div class="footer">
      <div class="note">Демо. Никаких данных не сохраняется на диск.</div>
    </div>
  </div>

  <div class="main">
    <div class="topbar">
      <div class="note" id="connection-status">Подключение...</div>
      <div class="pill" id="remote-info">Ожидание</div>
    </div>

    <div class="grid">
      <div class="panel">
        <div class="video-wrap" id="video-wrap">
          <video id="remoteVideo" autoplay playsinline></video>
          <video id="localVideo" autoplay playsinline muted style="width:200px;height:150px;border-radius:8px;position:absolute;right:16px;bottom:16px;"></video>

          <div id="incoming" class="incoming hide">
            <div>
              <div style="font-weight:700" id="incoming-from">Входящий звонок</div>
              <div class="small" id="incoming-from-sub">От: —</div>
            </div>
            <div style="display:flex;gap:8px">
              <button id="btn-accept" title="Принять">Принять</button>
              <button id="btn-decline" class="ghost" title="Отклонить">Отклонить</button>
            </div>
          </div>
        </div>

        <div class="controls">
          <div class="call-controls">
            <button id="btn-call" class="ghost">Позвонить</button>
            <button id="btn-end" class="danger hide">Завершить</button>
          </div>

          <div style="margin-left:auto;display:flex;gap:8px;align-items:center">
            <button id="btn-mic" class="btn-toggle">Мик</button>
            <button id="btn-cam" class="btn-toggle">Кам</button>
          </div>
        </div>

      </div>

      <div class="panel">
        <h3>Журнал / Статус</h3>
        <div id="log" style="margin-top:10px;flex:1;overflow:auto;background:rgba(255,255,255,0.02);padding:8px;border-radius:8px"></div>
        <div style="margin-top:10px">
          <label>Найти пользователя:</label>
          <input id="call-target" placeholder="логин для звонка" />
          <div style="margin-top:8px;display:flex;gap:8px">
            <button id="btn-call-target">Позвонить</button>
            <button id="btn-clear-log" class="ghost">Очистить</button>
          </div>
        </div>
      </div>
    </div>

  </div>
</div>

<script>
/*
  Client-side logic:
  - Connects via WebSocket to server for signaling.
  - Uses RTCPeerConnection with public STUN.
  - Allows registering/login via HTTP.
*/
const apiBase = '/api';
let ws;
let me = { username: '${escapeHtml(loggedUsername)}' };
let pc = null;
let localStream = null;
let remoteStream = null;
let currentTarget = null;
let isMuted = false;
let isCamOff = false;

const logEl = id('log');
const connectionStatus = id('connection-status');

function log(msg) {
  const el = document.createElement('div');
  el.textContent = '[' + new Date().toLocaleTimeString() + '] ' + msg;
  logEl.prepend(el);
}

function id(i){ return document.getElementById(i); }
function qsel(s){ return document.querySelector(s); }

function escapeHtml(s){ return (s||'').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":"&#39;"})[c]); }

function init() {
  attachUI();
  connectWS();

  // If already logged (cookie), update UI via server probe
  if(me.username) {
    showLogged(me.username);
  }
}

function attachUI() {
  id('btn-show-register').onclick = ()=>{ id('login-form').classList.add('hide'); id('register-form').classList.remove('hide'); };
  id('btn-cancel-register').onclick = ()=>{ id('register-form').classList.add('hide'); id('login-form').classList.remove('hide'); };
  id('btn-register').onclick = doRegister;
  id('btn-login').onclick = doLogin;
  id('btn-logout').onclick = doLogout;
  id('btn-copy').onclick = ()=>{ navigator.clipboard.writeText(me.username||''); alert('Скопировано'); };
  id('btn-search').onclick = fetchUsers;
  id('search-q').addEventListener('keypress', e => { if(e.key === 'Enter') fetchUsers(); });
  id('btn-call').onclick = ()=> initiateCallPrompt();
  id('btn-call-target').onclick = ()=> initiateCallTo(id('call-target').value.trim());
  id('btn-end').onclick = endCall;
  id('btn-accept').onclick = acceptIncoming;
  id('btn-decline').onclick = declineIncoming;
  id('btn-mic').onclick = toggleMic;
  id('btn-cam').onclick = toggleCam;
  id('btn-clear-log').onclick = ()=> logEl.innerHTML='';
}

async function doRegister(){
  const username = id('reg-username').value.trim();
  const password = id('reg-password').value;
  const displayName = id('reg-display').value.trim();
  if(!username||!password){ alert('Введите логин и пароль'); return; }
  const res = await fetch(apiBase + '/register', {method:'POST', headers:{'Content-Type':'application/json'}, body: JSON.stringify({username,password,displayName})});
  const data = await res.json();
  if(res.ok){ alert('Успешно, можете войти'); id('register-form').classList.add('hide'); id('login-form').classList.remove('hide'); }
  else alert(data.error || 'Ошибка');
}

async function doLogin(){
  const username = id('login-username').value.trim();
  const password = id('login-password').value;
  if(!username||!password){ alert('Введите логин и пароль'); return; }
  const res = await fetch(apiBase + '/login', {method:'POST', headers:{'Content-Type':'application/json'}, body: JSON.stringify({username,password})});
  const data = await res.json();
  if(res.ok){ me.username = username; showLogged(username); ws && wsReady() && sendWS({ type:'hello', from: username }); log('Вошли как ' + username); }
  else alert(data.error || 'Ошибка входа');
}

async function doLogout(){
  await fetch(apiBase + '/logout', {method:'POST'});
  document.cookie = 'username=;expires=Thu, 01 Jan 1970 00:00:00 GMT;path=/';
  me.username = null;
  showLogged(null);
  try{ ws && ws.close(); } catch(e){}
  location.reload();
}

function showLogged(username){
  if(username){
    id('me-name').textContent = username;
    id('logged').classList.remove('hide');
    id('login-form').classList.add('hide');
  } else {
    id('logged').classList.add('hide');
    id('login-form').classList.remove('hide');
  }
  // ensure websocket hello
  setTimeout(()=> { if(ws && ws.readyState === WebSocket.OPEN && me.username) sendWS({ type:'hello', from: me.username }); }, 500);
}

function connectWS(){
  const proto = (location.protocol === 'https:') ? 'wss' : 'ws';
  const url = proto + '://' + location.host;
  ws = new WebSocket(url);
  ws.onopen = () => {
    connectionStatus.textContent = 'Сигнализация: подключена';
    if(me.username) sendWS({ type:'hello', from: me.username });
    log('WS connected');
  };
  ws.onmessage = (ev) => {
    try {
      const msg = JSON.parse(ev.data);
      handleSignal(msg);
    } catch(e){ console.error(e); }
  };
  ws.onclose = ()=> { connectionStatus.textContent = 'Сигнализация: отключена'; log('WS closed'); setTimeout(connectWS, 2000); };
  ws.onerror = (e)=> console.error('WS error', e);
}

function wsReady(){ return ws && ws.readyState === WebSocket.OPEN; }
function sendWS(obj){ if(wsReady()) ws.send(JSON.stringify(obj)); else console.warn('WS not ready'); }

function handleSignal(msg){
  log('signal: ' + msg.type + (msg.from ? (' from ' + msg.from) : ''));
  if(msg.type === 'user-status'){
    // could update UI status
    updateUserStatus(msg.username, msg.online);
  } else if(msg.type === 'call-offer'){
    // incoming offer
    currentTarget = msg.from;
    showIncoming(msg.from);
    // store offer
    window._pendingOffer = msg;
  } else if(msg.type === 'call-answer'){
    // remote accepted; set remote desc
    const sdp = msg.payload;
    if(pc) pc.setRemoteDescription(new RTCSessionDescription(sdp));
  } else if(msg.type === 'ice-candidate'){
    if(pc && msg.payload) pc.addIceCandidate(new RTCIceCandidate(msg.payload).catch? new RTCIceCandidate(msg.payload): new RTCIceCandidate(msg.payload));
  } else if(msg.type === 'call-failed'){
    alert('Не удалось дозвониться: ' + (msg.reason || 'unknown'));
    endCall();
  } else if(msg.type === 'hello'){
    // ignore
  }
}

function updateUserStatus(username, online){
  const el = document.querySelector('[data-user="'+username+'"]');
  if(el){
    const dot = el.querySelector('.status-dot');
    dot.classList.toggle('status-online', !!online);
    dot.classList.toggle('status-off', !online);
  }
}

async function fetchUsers(){
  const q = id('search-q').value.trim();
  const res = await fetch(apiBase + '/users?q='+encodeURIComponent(q));
  const list = await res.json();
  const wrap = id('user-list');
  wrap.innerHTML = '';
  list.forEach(u => {
    const item = document.createElement('div');
    item.className = 'user-item';
    item.setAttribute('data-user', u.username);
    item.innerHTML = '<div style="width:36px;height:36px;border-radius:8px;background:linear-gradient(135deg,#7c5cff,#4ce1b6);display:flex;align-items:center;justify-content:center;">'+u.username.charAt(0).toUpperCase()+'</div>'
      + '<div style="flex:1"><div style="font-weight:700">'+escapeHtml(u.displayName)+'</div><div class="small muted">'+escapeHtml(u.username)+'</div></div>'
      + '<div style="display:flex;flex-direction:column;align-items:flex-end"><div class="status-dot '+(u.online?'status-online':'status-off')+'"></div><button class="ghost btn-call-user small" style="margin-top:8px">Позвонить</button></div>';
    wrap.appendChild(item);
    item.querySelector('.btn-call-user').onclick = ()=> initiateCallTo(u.username);
  });
}

function initiateCallPrompt(){
  const target = prompt('Кому позвонить? Введите логин:');
  if(target) initiateCallTo(target.trim());
}

async function initiateCallTo(target){
  if(!me.username){ alert('Сначала войдите'); return; }
  if(!target){ alert('Введите логин'); return; }
  currentTarget = target;
  log('Инициация звонка к ' + target);
  await prepareLocalMedia();
  createPeerConnection();
  // create offer
  const offer = await pc.createOffer();
  await pc.setLocalDescription(offer);
  // send offer via signaling
  sendWS({ type:'call-offer', from: me.username, to: target, payload: offer });
  // UI
  id('btn-end').classList.remove('hide');
  id('btn-call').classList.add('hide');
  id('remote-info').textContent = 'Звонок: ' + target;
}

async function prepareLocalMedia(){
  if(localStream) return;
  try {
    localStream = await navigator.mediaDevices.getUserMedia({ audio:true, video:true });
    id('localVideo').srcObject = localStream;
  } catch(e){
    alert('Не удалось получить доступ к камере/микрофону: ' + e.message);
    throw e;
  }
}

function createPeerConnection(){
  if(pc) return;
  pc = new RTCPeerConnection({ iceServers: [{ urls: 'stun:stun.l.google.com:19302' }] });
  remoteStream = new MediaStream();
  id('remoteVideo').srcObject = remoteStream;

  // add local tracks
  if(localStream){
    localStream.getTracks().forEach(t => pc.addTrack(t, localStream));
  }

  pc.ontrack = (ev) => {
    ev.streams[0].getTracks().forEach(track => remoteStream.addTrack(track));
  };

  pc.onicecandidate = (ev) => {
    if(ev.candidate){
      sendWS({ type:'ice-candidate', from: me.username, to: currentTarget, payload: ev.candidate });
    }
  };

  pc.onconnectionstatechange = ()=> {
    log('Peer connection: ' + pc.connectionState);
    if(pc.connectionState === 'disconnected' || pc.connectionState === 'failed' || pc.connectionState === 'closed'){
      endCall();
    }
  };
}

function showIncoming(from){
  id('incoming').classList.remove('hide');
  id('incoming-from').textContent = 'Входящий звонок';
  id('incoming-from-sub').textContent = 'От: ' + from;
  id('remote-info').textContent = 'Входящий от ' + from;
}

async function acceptIncoming(){
  id('incoming').classList.add('hide');
  const offer = window._pendingOffer && window._pendingOffer.payload;
  if(!offer){ alert('Не найден offer'); return; }
  currentTarget = window._pendingOffer.from;
  await prepareLocalMedia();
  createPeerConnection();
  await pc.setRemoteDescription(new RTCSessionDescription(offer));
  const answer = await pc.createAnswer();
  await pc.setLocalDescription(answer);
  sendWS({ type:'call-answer', from: me.username, to: currentTarget, payload: answer });
  id('btn-end').classList.remove('hide');
  id('btn-call').classList.add('hide');
  window._pendingOffer = null;
}

function declineIncoming(){
  id('incoming').classList.add('hide');
  if(window._pendingOffer && window._pendingOffer.from){
    sendWS({ type:'call-failed', from: me.username, to: window._pendingOffer.from, reason: 'rejected' });
  }
  window._pendingOffer = null;
}

function endCall(){
  try{
    if(pc){
      pc.getSenders().forEach(s => { try{s.track.stop();}catch(e){} });
      pc.close();
      pc = null;
    }
    if(localStream){
      localStream.getTracks().forEach(t => t.stop());
      localStream = null;
    }
    id('btn-end').classList.add('hide');
    id('btn-call').classList.remove('hide');
    id('remote-info').textContent = 'Ожидание';
    log('Звонок завершён');
    // notify remote
    if(currentTarget) sendWS({ type:'call-failed', from: me.username, to: currentTarget, reason: 'ended' });
    currentTarget = null;
  } catch(e){ console.error(e); }
}

function toggleMic(){
  if(!localStream) return;
  isMuted = !isMuted;
  localStream.getAudioTracks().forEach(t => t.enabled = !isMuted);
  id('btn-mic').textContent = isMuted ? 'Мик выключен' : 'Мик';
}

function toggleCam(){
  if(!localStream) return;
  isCamOff = !isCamOff;
  localStream.getVideoTracks().forEach(t => t.enabled = !isCamOff);
  id('btn-cam').textContent = isCamOff ? 'Кам выкл' : 'Кам';
}

// helper
function escapeHtml(s){ return (s||'').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":"&#39;"})[c]); }

document.addEventListener('DOMContentLoaded', init);
</script>
</body>
</html>`;
  return html;
}

// small escape for injected username
function escapeHtml(s){ if(!s) return ''; return String(s).replace(/[&<>"']/g, c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'})[c]); }